
# Site setting
title: adorablyfragileinfrastructure
#email: ben at nope dot nope
description: > # this means to ignore newlines until "baseurl:"
  stuffer of things, thinger of stuffs
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://adorably.fragileinfrastructure.com"
twitter_username: benwtr
github_username:  benwtr

exclude: [ "Gemfile", "Gemfile.lock", "CNAME" ]

gems: ["jekyll-gist"]

markdown: redcarpet
